<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PerguruanTinggi;
use Illuminate\Support\Str;

class PerguruanTinggiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode_pt' => '031001', 'nama_pt' => 'Universitas Ibnu Chaldun'],
            ['kode_pt' => '031003', 'nama_pt' => 'Universitas Islam Jakarta'],
            ['kode_pt' => '031005', 'nama_pt' => 'Universitas Jakarta'],
            ['kode_pt' => '031006', 'nama_pt' => 'Universitas Jayabaya'],
            ['kode_pt' => '031007', 'nama_pt' => 'Universitas Katolik Indonesia Atma Jaya'],
            ['kode_pt' => '031008', 'nama_pt' => 'Universitas Krisnadwipayana'],
            ['kode_pt' => '031009', 'nama_pt' => 'Universitas Kristen Indonesia'],
            ['kode_pt' => '031010', 'nama_pt' => 'Universitas Kristen Krida Wacana'],
            ['kode_pt' => '031011', 'nama_pt' => 'Universitas Muhammadiyah Jakarta'],
            ['kode_pt' => '031012', 'nama_pt' => 'Universitas Nasional'],
            ['kode_pt' => '031013', 'nama_pt' => 'Universitas Pancasila'],
            ['kode_pt' => '031014', 'nama_pt' => 'Universitas Prof Dr Moestopo (Beragama)'],
            ['kode_pt' => '031015', 'nama_pt' => 'Universitas Tarumanagara'],
            ['kode_pt' => '031016', 'nama_pt' => 'Universitas Trisakti'],
            ['kode_pt' => '031017', 'nama_pt' => 'Universitas 17 Agustus 1945 Jakarta'],
            ['kode_pt' => '031018', 'nama_pt' => 'Universitas Borobudur'],
            ['kode_pt' => '031019', 'nama_pt' => 'Universitas Mercu Buana'],
            ['kode_pt' => '031020', 'nama_pt' => 'Universitas Persada Indonesia Yai'],
            ['kode_pt' => '031021', 'nama_pt' => 'Universitas Islam As-syafiiyah'],
            ['kode_pt' => '031023', 'nama_pt' => 'Universitas Darma Persada'],
            ['kode_pt' => '031024', 'nama_pt' => 'Universitas Mpu Tantular'],
            ['kode_pt' => '031025', 'nama_pt' => 'Universitas Satya Negara Indonesia'],
            ['kode_pt' => '031026', 'nama_pt' => 'Universitas Yarsi'],
            ['kode_pt' => '031027', 'nama_pt' => 'Universitas Respati Indonesia'],
            ['kode_pt' => '031030', 'nama_pt' => 'Universitas Sahid'],
            ['kode_pt' => '031031', 'nama_pt' => 'Universitas Satyagama'],
            ['kode_pt' => '031033', 'nama_pt' => 'Universitas Esa Unggul'],
            ['kode_pt' => '031034', 'nama_pt' => 'Universitas Pelita Harapan'],
            ['kode_pt' => '031036', 'nama_pt' => 'Universitas Bhayangkara Jakarta Raya'],
            ['kode_pt' => '031037', 'nama_pt' => 'Universitas Gunadarma'],
            ['kode_pt' => '031038', 'nama_pt' => 'Universitas Bina Nusantara'],
            ['kode_pt' => '031039', 'nama_pt' => 'Universitas Muhammadiyah Prof Dr Hamka'],
            ['kode_pt' => '031041', 'nama_pt' => 'Universitas Paramadina'],
            ['kode_pt' => '031042', 'nama_pt' => 'Universitas Bung Karno'],
            ['kode_pt' => '031043', 'nama_pt' => 'Universitas Dirgantara Marsekal Suryadarma'],
            ['kode_pt' => '031044', 'nama_pt' => 'Universitas Al-Azhar Indonesia'],
            ['kode_pt' => '031045', 'nama_pt' => 'Universitas Budi Luhur'],
            ['kode_pt' => '031048', 'nama_pt' => 'Universitas Bunda Mulia'],
            ['kode_pt' => '031049', 'nama_pt' => 'Universitas Indraprasta PGRI'],
            ['kode_pt' => '031050', 'nama_pt' => 'Universitas Tama Jagakarsa'],
            ['kode_pt' => '031051', 'nama_pt' => 'Universitas Multimedia Nusantara Jakarta'],
            ['kode_pt' => '031053', 'nama_pt' => 'Universitas Bakrie'],
            ['kode_pt' => '031054', 'nama_pt' => 'Universitas Tanri Abeng'],
            ['kode_pt' => '031055', 'nama_pt' => 'Universitas Trilogi'],
            ['kode_pt' => '031056', 'nama_pt' => 'Universitas Sampoerna'],
            ['kode_pt' => '031057', 'nama_pt' => 'Universitas Agung Podomoro'],
            ['kode_pt' => '031059', 'nama_pt' => 'Universitas Mohammad Husni Thamrin Jakarta'],
            ['kode_pt' => '031061', 'nama_pt' => 'Universitas Nahdlatul Ulama Indonesia'],
            ['kode_pt' => '031062', 'nama_pt' => 'Universitas Pertamina'],
            ['kode_pt' => '031063', 'nama_pt' => 'Universitas Prasetiya Mulya'],
            ['kode_pt' => '031064', 'nama_pt' => 'Universitas Binawan'],
            ['kode_pt' => '031065', 'nama_pt' => 'Universitas Bina Sarana Informatika'],
            ['kode_pt' => '031066', 'nama_pt' => 'Universitas Dian Nusantara'],
            ['kode_pt' => '031067', 'nama_pt' => 'Universitas Pradita'],
            ['kode_pt' => '031068', 'nama_pt' => 'Universitas Siber Asia'],
            ['kode_pt' => '031069', 'nama_pt' => 'Universitas Nusa Mandiri'],
            ['kode_pt' => '031070', 'nama_pt' => 'Universitas Insan Cita Indonesia'],
            ['kode_pt' => '031071', 'nama_pt' => 'Universitas Media Nusantara Citra'],
            ['kode_pt' => '031072', 'nama_pt' => 'Universitas Indonesia Maju'],
            ['kode_pt' => '031073', 'nama_pt' => 'Universitas Saintek Muhammadiyah'],
            ['kode_pt' => '031074', 'nama_pt' => 'Universitas Darunnajah'],
            ['kode_pt' => '031076', 'nama_pt' => 'Universitas Asa Indonesia'],
            ['kode_pt' => '031077', 'nama_pt' => 'Universitas Teknologi Muhammadiyah Jakarta'],
            ['kode_pt' => '031078', 'nama_pt' => 'Universitas Siber Indonesia'],
            ['kode_pt' => '031079', 'nama_pt' => 'Universitas Jakarta Internasional'],
            ['kode_pt' => '031080', 'nama_pt' => 'Universitas LIA'],
            ['kode_pt' => '031081', 'nama_pt' => 'Universitas Mitra Bangsa'],
            ['kode_pt' => '031082', 'nama_pt' => 'Universitas Kalbis'],
            ['kode_pt' => '031083', 'nama_pt' => 'Universitas Ary Ginanjar'],
            ['kode_pt' => '031084', 'nama_pt' => 'Universitas Cakrawala'],
            ['kode_pt' => '031085', 'nama_pt' => 'Universitas Bhakti Pertiwi Indonesia'],
            ['kode_pt' => '032002', 'nama_pt' => 'Institut Kesenian Jakarta'],
            ['kode_pt' => '032004', 'nama_pt' => 'Institut Sains dan Teknologi Nasional'],
            ['kode_pt' => '032005', 'nama_pt' => 'Institut Ilmu Sosial dan Ilmu Politik Jakarta'],
            ['kode_pt' => '032006', 'nama_pt' => 'Institut Teknologi Indonesia'],
            ['kode_pt' => '032007', 'nama_pt' => 'Institut Teknologi Budi Utomo'],
            ['kode_pt' => '032008', 'nama_pt' => 'Institut Sains dan Teknologi Al-Kamal'],
            ['kode_pt' => '032009', 'nama_pt' => 'Institut Bisnis dan Informatika Kwik Kian Gie'],
            ['kode_pt' => '032011', 'nama_pt' => 'Institut Keuangan-Perbankan dan Informatika Asia Perbanas'],
            ['kode_pt' => '032012', 'nama_pt' => 'Institut Bisnis Nusantara'],
            ['kode_pt' => '032014', 'nama_pt' => 'Institut Bisnis dan Multimedia Asmi Jakarta'],
            ['kode_pt' => '032015', 'nama_pt' => 'Institut Bisnis dan Informatika (IBI) Kosgoro 1957'],
            ['kode_pt' => '032016', 'nama_pt' => 'Institut Bio Scientia Internasional Indonesia'],
            ['kode_pt' => '032017', 'nama_pt' => 'Institut Ilmu Sosial dan Manajemen STIAMI'],
            ['kode_pt' => '032018', 'nama_pt' => 'Institut Kesehatan Indonesia'],
            ['kode_pt' => '032020', 'nama_pt' => 'Institut Transportasi dan Logistik Trisakti'],
            ['kode_pt' => '032021', 'nama_pt' => 'Institut Teknologi Calvin'],
            ['kode_pt' => '032023', 'nama_pt' => 'Institut Teknologi dan Bisnis Ahmad Dahlan'],
            ['kode_pt' => '032025', 'nama_pt' => 'Institut Komunikasi dan Bisnis LSPR'],
            ['kode_pt' => '032026', 'nama_pt' => 'Institut Teknologi Perusahaan Listrik Negara'],
            ['kode_pt' => '032027', 'nama_pt' => 'Institut Teknologi dan Bisnis Swadharma'],
            ['kode_pt' => '032029', 'nama_pt' => 'Institut Kesehatan dan Teknologi Pondok Karya Pembangunan'],
            ['kode_pt' => '032030', 'nama_pt' => 'Institut Teknologi dan Bisnis Jakarta'],
            ['kode_pt' => '032031', 'nama_pt' => 'Institut Pariwisata Trisakti'],
            ['kode_pt' => '032032', 'nama_pt' => 'Institut Kesehatan Hermina'],
            ['kode_pt' => '032033', 'nama_pt' => 'Institut Bisnis dan Komunikasi Swadaya'],
            ['kode_pt' => '032034', 'nama_pt' => 'Institut Tarumanagara'],
            ['kode_pt' => '032035', 'nama_pt' => 'Institut IPMI'],
            ['kode_pt' => '032036', 'nama_pt' => 'Institut Pariwisata Tedja Indonesia'],
            ['kode_pt' => '032037', 'nama_pt' => 'Institut Media Digital EMTEK'],
            ['kode_pt' => '032038', 'nama_pt' => 'Institut Sosial dan Teknologi Widuri'],
            ['kode_pt' => '033001', 'nama_pt' => 'Sekolah Tinggi Filsafat Driyarkara'],
            ['kode_pt' => '033009', 'nama_pt' => 'Sekolah Tinggi Filsafat Theologi Jakarta'],
            ['kode_pt' => '033012', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Indonesia Jakarta'],
            ['kode_pt' => '033014', 'nama_pt' => 'Sekolah TInggi Keguruan dan Ilmu Pendidikan Kusuma Negara'],
            ['kode_pt' => '033022', 'nama_pt' => 'Sekolah Tinggi Manajemen Informatika dan Komputer Jakarta STI&K'],
            ['kode_pt' => '033024', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi YAI'],
            ['kode_pt' => '033032', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Kusuma Negara'],
            ['kode_pt' => '033034', 'nama_pt' => 'STMIK Kuwera'],
            ['kode_pt' => '033038', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Bhakti Pembangunan'],
            ['kode_pt' => '033040', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Tri Dharma Widya'],
            ['kode_pt' => '033044', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Nasional Indonesia'],
            ['kode_pt' => '033059', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Jayakarta'],
            ['kode_pt' => '033060', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Bisnis Indonesia'],
            ['kode_pt' => '033064', 'nama_pt' => 'Sekolah Tinggi Manajemen Labora'],
            ['kode_pt' => '033066', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Trisakti'],
            ['kode_pt' => '033069', 'nama_pt' => 'Sekolah Tinggi Manajemen Ppm'],
            ['kode_pt' => '033070', 'nama_pt' => 'Sekolah Tinggi Penerbangan Aviasi'],
            ['kode_pt' => '033072', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi IGI'],
            ['kode_pt' => '033073', 'nama_pt' => 'Sekolah Tinggi Ilmu Hukum IBLAM'],
            ['kode_pt' => '033076', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Ganesha'],
            ['kode_pt' => '033080', 'nama_pt' => 'STMIK Jayakarta'],
            ['kode_pt' => '033086', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Taman Siswa'],
            ['kode_pt' => '033087', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Trianandra'],
            ['kode_pt' => '033094', 'nama_pt' => 'Sekolah Tinggi Perpajakan Indonesia'],
            ['kode_pt' => '033106', 'nama_pt' => 'Sekolah Tinggi Ilmu Komunikasi Inter Studi'],
            ['kode_pt' => '033107', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Tunas Nusantara'],
            ['kode_pt' => '033115', 'nama_pt' => 'STIE Pengembangan Bisnis dan Manajemen'],
            ['kode_pt' => '033117', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Sint Carolus'],
            ['kode_pt' => '033119', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Jayakusuma'],
            ['kode_pt' => '033120', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Kasih Bangsa'],
            ['kode_pt' => '033121', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Dharma Bumi Putra'],
            ['kode_pt' => '033126', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Wiyatamandala'],
            ['kode_pt' => '033137', 'nama_pt' => 'Sekolah Tinggi Bahasa Asing IEC Jakarta'],
            ['kode_pt' => '033138', 'nama_pt' => 'Sekolah Tinggi Ilmu Maritim Ami'],
            ['kode_pt' => '033139', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Pamentas'],
            ['kode_pt' => '033143', 'nama_pt' => 'Sekolah Tinggi Manajemen Transportasi Malahayati'],
            ['kode_pt' => '033150', 'nama_pt' => 'ST Ilmu Komputer Cipta Karya Informatika'],
            ['kode_pt' => '033152', 'nama_pt' => 'Sekolah Tinggi Manajemen Asuransi Trisakti'],
            ['kode_pt' => '033154', 'nama_pt' => 'Sekolah Tinggi Ilmu Komunikasi Profesi Indonesia'],
            ['kode_pt' => '033156', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Medistra Indonesia'],
            ['kode_pt' => '033157', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Widya Persada'],
            ['kode_pt' => '033167', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Kesosi'],
            ['kode_pt' => '033168', 'nama_pt' => 'STIE Indonesia Banking School'],
            ['kode_pt' => '033170', 'nama_pt' => 'STIKES Persada Husada Indonesia'],
            ['kode_pt' => '033171', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Mitra Ria Husada Jakarta'],
            ['kode_pt' => '033173', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Abdi Nusantara'],
            ['kode_pt' => '033175', 'nama_pt' => 'Sekolah Tinggi Teknologi Informasi NIIT'],
            ['kode_pt' => '033176', 'nama_pt' => 'Sekolah Tinggi Manajemen Risiko dan Asuransi'],
            ['kode_pt' => '033177', 'nama_pt' => 'Sekolah Tinggi Ilmu Pemerintahan Abdi Negara'],
            ['kode_pt' => '033182', 'nama_pt' => 'STIBA Indonesia LPI'],
            ['kode_pt' => '033183', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi Santa Ursula'],
            ['kode_pt' => '033184', 'nama_pt' => 'Sekolah Tinggi Desain Interstudi'],
            ['kode_pt' => '033188', 'nama_pt' => 'STIE Unisadhuguna'],
            ['kode_pt' => '033189', 'nama_pt' => 'Sekolah Tinggi Internasional Konservatori Musik Indonesia'],
            ['kode_pt' => '033190', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Pertamedika'],
            ['kode_pt' => '033194', 'nama_pt' => 'Sekolah Tinggi Ilmu Komunikasi dan Sekretari Tarakanita'],
            ['kode_pt' => '033195', 'nama_pt' => 'Sekolah Tinggi Media Komunikasi Trisakti'],
            ['kode_pt' => '033199', 'nama_pt' => 'Sekolah Tinggi Desain LaSalle'],
            ['kode_pt' => '033203', 'nama_pt' => 'Sekolah Tinggi Ilmu Ekonomi BPKP'],
            ['kode_pt' => '033205', 'nama_pt' => 'Sekolah Tinggi Kepemerintahan dan Kebijakan Publik'],
            ['kode_pt' => '033208', 'nama_pt' => 'Sekolah Tinggi Hukum Indonesia Jentera'],
            ['kode_pt' => '033209', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Mitra Keluarga'],
            ['kode_pt' => '033210', 'nama_pt' => 'STIH Litigasi'],
            ['kode_pt' => '033215', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Budi Kemuliaan'],
            ['kode_pt' => '033216', 'nama_pt' => 'Sekolah Tinggi Manajemen Informatika dan Komputer Indo Daya Suvana'],
            ['kode_pt' => '033217', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan RS Husada'],
            ['kode_pt' => '033219', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan IKIFA'],
            ['kode_pt' => '033220', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan RSPAD Gatot Soebroto'],
            ['kode_pt' => '033221', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Fatmawati'],
            ['kode_pt' => '033222', 'nama_pt' => 'Sekolah Tinggi Ilmu Hukum Profesor Gayus Lumbuun'],
            ['kode_pt' => '033223', 'nama_pt' => 'Sekolah Tinggi Ilmu Hukum Adhyaksa'],
            ['kode_pt' => '033224', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Sumber Waras'],
            ['kode_pt' => '033225', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Mayapada'],
            ['kode_pt' => '033226', 'nama_pt' => 'Sekolah Tinggi Manajemen Pariwisata dan Logistik Lentera Mondial'],
            ['kode_pt' => '033227', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan PGI Cikini'],
            ['kode_pt' => '033228', 'nama_pt' => 'Sekolah Tinggi Teknologi Pekerjaan Umum'],
            ['kode_pt' => '033229', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Pasar Rebo'],
            ['kode_pt' => '033230', 'nama_pt' => 'Sekolah Tinggi Ilmu Kesehatan Keris Husada'],
            ['kode_pt' => '034004', 'nama_pt' => 'Akademi Akuntansi Borobudur'],
            ['kode_pt' => '034011', 'nama_pt' => 'Akademi Akuntansi YAI Jakarta'],
            ['kode_pt' => '034024', 'nama_pt' => 'Akademi Teknologi Grafika Indonesia Jakarta'],
            ['kode_pt' => '034030', 'nama_pt' => 'Akademi Maritim Nasional Jaya'],
            ['kode_pt' => '034033', 'nama_pt' => 'Akademi Keuangan dan Perbankan Borobudur'],
            ['kode_pt' => '034058', 'nama_pt' => 'Akademi Maritim Djadajat'],
            ['kode_pt' => '034083', 'nama_pt' => 'Akademi Seni Rupa dan Desain ISWI Jakarta'],
            ['kode_pt' => '034095', 'nama_pt' => 'Akademi Kimia Analis Caraka Nusantara'],
            ['kode_pt' => '034102', 'nama_pt' => 'Akademi Pariwisata Nusantara Jaya'],
            ['kode_pt' => '034103', 'nama_pt' => 'Akademi Pariwisata Paramitha Jakarta'],
            ['kode_pt' => '034105', 'nama_pt' => 'Akademi Sekretari dan Manajemen Don Bosco'],
            ['kode_pt' => '034112', 'nama_pt' => 'Akademi Komunikasi Media Radio dan TV Jakarta'],
            ['kode_pt' => '034119', 'nama_pt' => 'Akademi Telekomunikasi Indonesia Gemilang'],
            ['kode_pt' => '034120', 'nama_pt' => 'Akademi Pariwisata Jakarta'],
            ['kode_pt' => '034121', 'nama_pt' => 'Akademi Maritim Pembangunan Jakarta'],
            ['kode_pt' => '034130', 'nama_pt' => 'Akademi Pariwisata Gsp Internasional'],
            ['kode_pt' => '034135', 'nama_pt' => 'Akademi Sekretari Interstudi'],
            ['kode_pt' => '034136', 'nama_pt' => 'Akademi Sekretari & Manajemen Dharma Budhi Bhakti'],
            ['kode_pt' => '034141', 'nama_pt' => 'AMIK Laksi-31'],
            ['kode_pt' => '034145', 'nama_pt' => 'Akademi Sekretari Saint Theresia'],
            ['kode_pt' => '034147', 'nama_pt' => 'Akademi Teknik Informatika Tunas Bangsa'],
            ['kode_pt' => '034154', 'nama_pt' => 'Akademi Kebidanan Pelita Persada'],
            ['kode_pt' => '034160', 'nama_pt' => 'Akademi Kebidanan Sismadi'],
            ['kode_pt' => '034168', 'nama_pt' => 'Akademi Komunikasi SAE Indonesia'],
            ['kode_pt' => '034169', 'nama_pt' => 'Akademi Kebidanan Mitra Persahabatan'],
            ['kode_pt' => '034175', 'nama_pt' => 'Akademi Kebidanan Farama Mulya'],
            ['kode_pt' => '034179', 'nama_pt' => 'Akademi Keperawatan Yaspen Jakarta'],
            ['kode_pt' => '034187', 'nama_pt' => 'Akademi Keperawatan Berkala Widya Husada'],
            ['kode_pt' => '034191', 'nama_pt' => 'Akademi Keperawatan Harum'],
            ['kode_pt' => '034195', 'nama_pt' => 'Akademi Perekam Medis dan Infokes Bhumi Husada'],
            ['kode_pt' => '034197', 'nama_pt' => 'Akademi Farmasi Bhumi Husada'],
            ['kode_pt' => '034199', 'nama_pt' => 'Akademi Refraksi Optisi Kartika Indera Persada'],
            ['kode_pt' => '034209', 'nama_pt' => 'Akademi Keperawatan Bina Insan Jakarta'],
            ['kode_pt' => '034210', 'nama_pt' => 'Akademi Keperawatan POLRI'],
            ['kode_pt' => '034211', 'nama_pt' => 'Akademi Keperawatan Husada Karya Jaya'],
            ['kode_pt' => '034223', 'nama_pt' => 'Akademi Keperawatan Pelni'],
            ['kode_pt' => '034225', 'nama_pt' => 'Akademi Kesehatan Gigi Ditkesad Jakarta'],
            ['kode_pt' => '034226', 'nama_pt' => 'Akademi Keperawatan Andalusia Jakarta'],
            ['kode_pt' => '034227', 'nama_pt' => 'Akademi Kesehatan Lingkungan Andalusia'],
            ['kode_pt' => '034228', 'nama_pt' => 'Akademi Gizi Andalusia'],
            ['kode_pt' => '034230', 'nama_pt' => 'Akademi Refraksi Optisi dan Optometry Gapopin'],
            ['kode_pt' => '034234', 'nama_pt' => 'Akademi Teknik Radiodiagnostik dan Radioterapi Nusantara'],
            ['kode_pt' => '034235', 'nama_pt' => 'Akademi Keperawatan Yayasan Dharma Bhakti Jakarta'],
            ['kode_pt' => '034237', 'nama_pt' => 'Akademi Refraksi Optisi Leprindo Jakarta'],
            ['kode_pt' => '034239', 'nama_pt' => 'Akademi Keperawatan Andakara'],
            ['kode_pt' => '034240', 'nama_pt' => 'Akademi Teknik Elektromedik Andakara'],
            ['kode_pt' => '034241', 'nama_pt' => 'Akademi Bakti Kemanusiaan Palang Merah Indonesia'],
            ['kode_pt' => '034242', 'nama_pt' => 'Akademi Olahraga Prestasi Nasional'],
            ['kode_pt' => '034243', 'nama_pt' => 'Akademi Kesehatan Yayasan Rumah Sakit Jakarta'],
            ['kode_pt' => '034244', 'nama_pt' => 'Akademi Bisnis Martha Tilaar'],
            ['kode_pt' => '035006', 'nama_pt' => 'Politeknik Tugu Jakarta'],
            ['kode_pt' => '035008', 'nama_pt' => 'Politeknik LP3I Jakarta'],
            ['kode_pt' => '035010', 'nama_pt' => 'Politeknik Karya Husada'],
            ['kode_pt' => '035012', 'nama_pt' => 'Politeknik Soca'],
            ['kode_pt' => '035014', 'nama_pt' => 'Politeknik Bentara Citra Bangsa'],
            ['kode_pt' => '035015', 'nama_pt' => 'Politeknik Bisnis dan Pasar Modal'],
            ['kode_pt' => '035016', 'nama_pt' => 'Politeknik Sahid'],
            ['kode_pt' => '035017', 'nama_pt' => 'Politeknik Hang Tuah Jakarta'],
            ['kode_pt' => '035018', 'nama_pt' => 'Politeknik Jakarta Internasional'],
            ['kode_pt' => '035020', 'nama_pt' => 'Politeknik Tempo'],
            ['kode_pt' => '035021', 'nama_pt' => 'Politeknik Astra'],
            ['kode_pt' => '035022', 'nama_pt' => 'Politeknik Multimedia Nusantara'],
            ['kode_pt' => '035023', 'nama_pt' => 'Politeknik Kartini Jakarta'],
            ['kode_pt' => '035024', 'nama_pt' => 'Politeknik Kreatif Indonesia'],
            ['kode_pt' => '035025', 'nama_pt' => 'Politeknik Prestasi Prima'],
            ['kode_pt' => '035026', 'nama_pt' => 'Politeknik Arutala Johana Hendarto'],
            ['kode_pt' => '036002', 'nama_pt' => 'Akademi Komunitas Bisnis Internasional'],
        ];

        foreach ($data as $item) {
            PerguruanTinggi::create([
                'uuid' => Str::uuid(),
                'kode_pt' => $item['kode_pt'],
                'nama_pt' => $item['nama_pt'],
                'jenis_pt' => 'PTS',
                'status_pt' => 'Aktif',
            ]);
        }
    }
}